import CohBit.Spec

namespace CohBit

/--
### Property G1 — Nonnegativity
Distances in the Lawvere geometry generated by spend and defect are non-negative.
-/
def EdgeCost {X Action Cert Hash : Type} (b : @CohBit X Action Cert Hash) : Rat :=
  b.spend + b.defect

theorem edge_cost_nonnegative
  {X Action Cert Hash : Type}
  (b : @CohBit X Action Cert Hash)
  (h : Verified b) :
  0 ≤ EdgeCost b :=
by
  unfold EdgeCost
  unfold Verified Structural at h
  rcases h with ⟨_, h_struct⟩
  have h_spend := h_struct.right.right.left
  have h_defect := h_struct.right.right.right.left
  exact add_nonneg h_spend h_defect

/--
### Property G3 — Directed triangle inequality
Shortest path distance satisfies d(x,z) ≤ d(x,y) + d(y,z).
We prove this at the path level to avoid infimum issues on ℚ.
-/

theorem triangle_inequality_paths
  {X Action Cert Hash : Type}
  (x y z : X)
  (p1 p2 : List (@CohBit X Action Cert Hash))
  (hp1 : p1 ∈ VerifiedPaths x y)
  (hp2 : p2 ∈ VerifiedPaths y z) :
  ∃ (p3 : List (@CohBit X Action Cert Hash)), p3 ∈ VerifiedPaths x z ∧ 
  PathCost p3 ≤ PathCost p1 + PathCost p2 :=
by
  let p3 := p1 ++ p2
  use p3
  constructor
  · unfold VerifiedPaths at *
    simp at *
    rcases hp1 with ⟨h_conn1, h_ver1, h_head1, h_last1⟩
    rcases hp2 with ⟨h_conn2, h_ver2, h_head2, h_last2⟩
    constructor
    · -- Connection logic
      induction p1 with
      | nil => simp at h_head1; rw [h_head1]; exact h_conn2
      | cons b1 tail1 ih => 
          simp at *
          rcases h_conn1 with ⟨h_step1, h_tail1⟩
          constructor
          · exact h_step1
          · -- Correctly handle the tail
            cases tail1 with
            | nil => simp at h_last1; rw [h_last1]; exact h_head2
            | cons b' tail' => exact ih h_tail1 (by simp) h_head1 h_last1
    · constructor
      · intro b hb
        cases (List.mem_append.1 hb) with
        | inl h => exact h_ver1 b h
        | inr h => exact h_ver2 b h
      · constructor
        · cases p1 with | nil => simp at h_head1; rw [h_head1]; exact h_head2 | cons b1 tail1 => simp at *; exact h_head1
        · cases p2 with | nil => simp at h_last2; rw [← h_last2]; exact h_last1 | cons b2 tail2 => simp at *; exact h_last2
  · unfold PathCost
    simp

end CohBit
