// @cohbit/tooling — T17 Audit / Report Generator
// Generates cross-system audit reports from tool registry, repair queue,
// and atlas store state.
// Spec: Noetican Tooling Layer v0.1 §19

import { TOOL_REGISTRY } from './T0_registry.js';
import { REPAIR_QUEUE } from './T8_repair_queue.js';

export interface AuditReport {
    generatedAt: string;
    toolRegistry: {
        toolCount: number;
        tools: Array<{ id: string; type: string; trustLevel: string }>;
    };
    repairQueue: {
        totalCount: number;
        openCount: number;
        byPriority: Record<string, number>;
        byCategory: Record<string, number>;
    };
    atlasStore: {
        entryCount: number;
        recentEntries: string[];
    };
    overallStatus: 'healthy' | 'warning' | 'degraded';
    recommendations: string[];
}

/**
 * Generate a full audit report from current system state.
 * Pulls from tool registry, repair queue, and atlas store.
 */
export function generateAuditReport(
    atlasEntryCount?: number,
    recentAtlasEntries?: string[],
): AuditReport {
    // Tool registry
    const toolCount = TOOL_REGISTRY.size;
    const tools = [...TOOL_REGISTRY.values()].map(t => ({
        id: t.toolId, type: t.toolType, trustLevel: t.trustLevel,
    }));

    // Repair queue
    const openRepairs = REPAIR_QUEUE.filter(r => r.status === 'open');
    const byPriority: Record<string, number> = {};
    const byCategory: Record<string, number> = {};
    for (const r of REPAIR_QUEUE) {
        byPriority[r.priority] = (byPriority[r.priority] ?? 0) + 1;
        byCategory[r.repairType] = (byCategory[r.repairType] ?? 0) + 1;
    }

    // Status determination
    let overallStatus: AuditReport['overallStatus'] = 'healthy';
    const recommendations: string[] = [];

    if (openRepairs.length > 5) {
        overallStatus = 'degraded';
        recommendations.push(`High repair backlog: ${openRepairs.length} open repairs. Prioritize high-severity items.`);
    } else if (openRepairs.length > 0) {
        overallStatus = 'warning';
        recommendations.push(`${openRepairs.length} open repairs. Consider completing them before new commits.`);
    }

    if (toolCount < 3) {
        overallStatus = 'degraded';
        recommendations.push('Tool registry has fewer than 3 registered tools. Verify tool layer integrity.');
    }

    if (!atlasEntryCount || atlasEntryCount === 0) {
        recommendations.push('Atlas store is empty. No receipted memories persist. Consider running a pipeline.');
    }

    return {
        generatedAt: new Date().toISOString(),
        toolRegistry: { toolCount, tools },
        repairQueue: {
            totalCount: REPAIR_QUEUE.length,
            openCount: openRepairs.length,
            byPriority,
            byCategory,
        },
        atlasStore: {
            entryCount: atlasEntryCount ?? 0,
            recentEntries: recentAtlasEntries ?? [],
        },
        overallStatus,
        recommendations,
    };
}

/**
 * Generate a Markdown-formatted audit report string.
 */
export function generateAuditMarkdown(
    atlasEntryCount?: number,
    recentAtlasEntries?: string[],
): string {
    const report = generateAuditReport(atlasEntryCount, recentAtlasEntries);

    const lines: string[] = [
        `# CohBit-Copilot Audit Report`,
        `**Generated:** ${report.generatedAt}`,
        `**Overall Status:** ${report.overallStatus.toUpperCase()}`,
        '',
        '## Tool Registry',
        `- Tools registered: **${report.toolRegistry.toolCount}**`,
    ];
    for (const t of report.toolRegistry.tools) {
        lines.push(`  - \`${t.id}\` (${t.type}, ${t.trustLevel})`);
    }

    lines.push('', '## Repair Queue',
        `- Total tasks: ${report.repairQueue.totalCount}`,
        `- Open: ${report.repairQueue.openCount}`,
    );

    if (Object.keys(report.repairQueue.byPriority).length > 0) {
        lines.push('- By priority:');
        for (const [p, c] of Object.entries(report.repairQueue.byPriority)) {
            lines.push(`  - ${p}: ${c}`);
        }
    }

    lines.push('', '## Atlas Store',
        `- Total entries: ${report.atlasStore.entryCount}`,
    );

    lines.push('', '## Recommendations');
    if (report.recommendations.length === 0) {
        lines.push('- No issues detected. System is healthy.');
    } else {
        for (const r of report.recommendations) {
            lines.push(`- ${r}`);
        }
    }

    lines.push('', '---', '*Report generated by @cohbit/tooling T17 Audit Reporter.*');
    return lines.join('\n');
}