// @cohbit/math-atlas — M5 Mathematical Invariant Layer (25 MINV_MATH types)
// Spec: v0.1 §9 — The mathematical anchor that survives across models

export interface MathInvariant {
    id: string; name: string; definition: string;
    preserveAcrossModels: string[]; failureModes: string[]; receiptRequired: boolean;
}

export const MINV_MATH_001: MathInvariant = { id: 'MINV_MATH_001', name: 'IdentityPreservation', definition: 'A mapping preserves the identity or distinguishability of the relevant mathematical objects.', preserveAcrossModels: ['object identity', 'source-target correspondence', 'distinguishable elements'], failureModes: ['distinct objects collapsed', 'identity confused with equivalence', 'source object lost in target model'], receiptRequired: true };
export const MINV_MATH_002: MathInvariant = { id: 'MINV_MATH_002', name: 'CompositionPreservation', definition: 'Composed operations, paths, morphisms, or transitions preserve their composition law under mapping.', preserveAcrossModels: ['composition order', 'composed result', 'identity behavior when relevant'], failureModes: ['composition order reversed', 'composition law omitted', 'local mapping fails globally'], receiptRequired: true };
export const MINV_MATH_003: MathInvariant = { id: 'MINV_MATH_003', name: 'OrderPreservation', definition: 'A relation of precedence, comparison, refinement, or dependency is preserved under a mapping.', preserveAcrossModels: ['preorder or partial order', 'monotonic direction', 'dependency direction'], failureModes: ['order reversed', 'incomparables forced comparable', 'monotonicity assumed but not shown'], receiptRequired: true };
export const MINV_MATH_004: MathInvariant = { id: 'MINV_MATH_004', name: 'BoundaryPreservation', definition: 'A boundary, limit, constraint frontier, or admissible region remains distinguishable after translation between models.', preserveAcrossModels: ['inside/outside distinction', 'boundary condition', 'limit condition'], failureModes: ['boundary erased', 'soft constraint treated as hard boundary', 'limit condition omitted'], receiptRequired: true };
export const MINV_MATH_005: MathInvariant = { id: 'MINV_MATH_005', name: 'ConstraintSatisfaction', definition: 'A candidate object, state, path, proof step, or transition satisfies declared constraints under the selected model.', preserveAcrossModels: ['constraint identity', 'satisfaction condition', 'failure condition'], failureModes: ['constraint omitted', 'constraint weakened', 'constraint satisfaction assumed without check'], receiptRequired: true };
export const MINV_MATH_006: MathInvariant = { id: 'MINV_MATH_006', name: 'AdmissibleTransition', definition: 'A transition may be accepted only when declared admissibility conditions are satisfied under the chosen model.', preserveAcrossModels: ['source state', 'target state', 'transition rule', 'admissibility predicate', 'failure condition'], failureModes: ['possible treated as admissible', 'predicate omitted', 'domain changed silently', 'transition committed without witness'], receiptRequired: true };
export const MINV_MATH_007: MathInvariant = { id: 'MINV_MATH_007', name: 'WitnessPreservation', definition: 'A claim that depends on existence, verification, or construction preserves its witness or proof-relevant evidence.', preserveAcrossModels: ['witness object', 'witness role', 'verification relation'], failureModes: ['existence claimed without witness', 'witness erased in translation', 'computational witness treated as formal proof'], receiptRequired: true };
export const MINV_MATH_008: MathInvariant = { id: 'MINV_MATH_008', name: 'ProofObligationPreservation', definition: 'A mapping preserves what must still be proven, rather than hiding proof gaps behind a new representation.', preserveAcrossModels: ['proof obligations', 'unproved conditions', 'dependency claims'], failureModes: ['proof gap hidden', 'assumption promoted to theorem', 'simulation treated as discharged proof'], receiptRequired: true };
export const MINV_MATH_009: MathInvariant = { id: 'MINV_MATH_009', name: 'ResourceBoundPreservation', definition: 'A mathematical or computational bound remains visible under translation, simulation, or implementation.', preserveAcrossModels: ['bound statement', 'resource type', 'scaling condition'], failureModes: ['bound omitted', 'finite test generalized', 'complexity claim overstated'], receiptRequired: true };
export const MINV_MATH_010: MathInvariant = { id: 'MINV_MATH_010', name: 'StabilityPreservation', definition: 'A stability, persistence, convergence, or non-fragmentation property remains visible under the chosen mapping.', preserveAcrossModels: ['stability condition', 'disturbance model', 'failure threshold'], failureModes: ['local stability treated as global', 'empirical stability treated as theorem', 'failure threshold omitted'], receiptRequired: true };
export const MINV_MATH_011: MathInvariant = { id: 'MINV_MATH_011', name: 'ContinuationSupport', definition: 'A path, process, proof, computation, or transition remains supportable after the proposed step.', preserveAcrossModels: ['continuation condition', 'support requirement', 'blocking condition'], failureModes: ['step accepted though continuation fails', 'future constraint ignored', 'local success treated as admissible continuation'], receiptRequired: true };
export const MINV_MATH_012: MathInvariant = { id: 'MINV_MATH_012', name: 'FailureVisibility', definition: 'Failure modes remain explicit rather than hidden inside notation, analogy, implementation, or proof sketch.', preserveAcrossModels: ['failure condition', 'failure location', 'failure consequence'], failureModes: ['failure case omitted', 'counterexample hidden', 'edge case ignored'], receiptRequired: true };
export const MINV_MATH_013: MathInvariant = { id: 'MINV_MATH_013', name: 'Repairability', definition: 'A failed mapping, proof step, simulation, or definition can generate a structured repair obligation.', preserveAcrossModels: ['failure reason', 'repair target', 'verification route'], failureModes: ['failed proof abandoned without record', 'definition patched without receipt', 'repair changes theorem silently'], receiptRequired: true };
export const MINV_MATH_014: MathInvariant = { id: 'MINV_MATH_014', name: 'NonCollapseBoundary', definition: 'A mapping between mathematical models must not collapse distinct meanings, structures, or evidence levels into a false equivalence.', preserveAcrossModels: ['source model identity', 'target model identity', 'mapping limitation', 'non-equivalence warning'], failureModes: ['analogy treated as theorem', 'simulation treated as proof', 'diagram treated as formal definition', 'code treated as mathematical proof without specification'], receiptRequired: true };
export const MINV_MATH_015: MathInvariant = { id: 'MINV_MATH_015', name: 'Traceability', definition: 'A mathematical claim, mapping, or proof step remains traceable to source artifact, assumptions, evidence, and receipt.', preserveAcrossModels: ['source artifact', 'assumption record', 'evidence record', 'receipt'], failureModes: ['claim has no source', 'assumptions detached', 'evidence missing', 'receipt not linked'], receiptRequired: true };
export const MINV_MATH_016: MathInvariant = { id: 'MINV_MATH_016', name: 'ReversibilityCondition', definition: 'A mapping records whether and under what conditions it may be reversed.', preserveAcrossModels: ['forward map', 'reverse map if available', 'lost information', 'irreversibility condition'], failureModes: ['non-invertible map treated as reversible', 'lossy projection treated as equivalence', 'reverse claim omitted'], receiptRequired: true };
export const MINV_MATH_017: MathInvariant = { id: 'MINV_MATH_017', name: 'Monotonicity', definition: 'A mapping or process preserves direction of increase, refinement, dependency, admissibility, or information order where required.', preserveAcrossModels: ['monotone relation', 'direction', 'domain of monotonicity'], failureModes: ['monotonicity assumed globally', 'direction reversed', 'partial order collapsed into total order'], receiptRequired: true };
export const MINV_MATH_018: MathInvariant = { id: 'MINV_MATH_018', name: 'EquivalenceCondition', definition: 'An equivalence claim must state the relation, domain, preserved structure, and proof requirement.', preserveAcrossModels: ['equivalence relation', 'domain', 'preserved structure', 'proof condition'], failureModes: ['similarity treated as equivalence', 'bijection assumed', 'semantic equivalence unproved'], receiptRequired: true };
export const MINV_MATH_019: MathInvariant = { id: 'MINV_MATH_019', name: 'ApproximationBound', definition: 'An approximation, discretization, numerical method, or simulation must state its error, tolerance, or limitation boundary.', preserveAcrossModels: ['approximation type', 'error bound', 'valid range', 'tolerance'], failureModes: ['approximation treated as exact', 'numerical tolerance omitted', 'finite resolution hides instability'], receiptRequired: true };
export const MINV_MATH_020: MathInvariant = { id: 'MINV_MATH_020', name: 'FormalizationEligibility', definition: 'A mathematical claim is eligible for formalization only when definitions, assumptions, statement boundaries, and proof obligations are sufficiently explicit.', preserveAcrossModels: ['definitions', 'assumptions', 'theorem statement', 'proof obligations'], failureModes: ['informal idea sent to Lean too early', 'undefined term blocks theorem', 'claim changes during formalization'], receiptRequired: true };
export const MINV_MATH_021: MathInvariant = { id: 'MINV_MATH_021', name: 'DomainPreservation', definition: 'A mathematical statement or mapping must preserve the domain over which it is valid.', preserveAcrossModels: ['source domain', 'target domain', 'validity boundary'], failureModes: ['finite domain generalized to infinite', 'discrete result treated as continuous', 'abstract model treated as physical system'], receiptRequired: true };
export const MINV_MATH_022: MathInvariant = { id: 'MINV_MATH_022', name: 'AssumptionVisibility', definition: 'Assumptions required for a mathematical claim must remain explicit across representations, mappings, and retrieval.', preserveAcrossModels: ['declared assumptions', 'hidden assumptions found', 'dependency assumptions'], failureModes: ['assumption hidden', 'assumption treated as conclusion', 'model idealization omitted'], receiptRequired: true };
export const MINV_MATH_023: MathInvariant = { id: 'MINV_MATH_023', name: 'ModelScopeBoundary', definition: 'A model-specific statement must not be reused outside the model scope without a new mapping and receipt.', preserveAcrossModels: ['model scope', 'reuse boundary', 'required mapping'], failureModes: ['graph property reused as geometric theorem', 'simulation model treated as physical law', 'category analogy treated as implementation guarantee'], receiptRequired: true };
export const MINV_MATH_024: MathInvariant = { id: 'MINV_MATH_024', name: 'EvidenceClaimAlignment', definition: 'The strength of a mathematical claim must not exceed the evidence level supporting it.', preserveAcrossModels: ['claim type', 'evidence level', 'allowed claim ceiling', 'forbidden upgrade'], failureModes: ['proof sketch described as proof', 'simulation described as theorem', 'Lean statement described as checked'], receiptRequired: true };
export const MINV_MATH_025: MathInvariant = { id: 'MINV_MATH_025', name: 'ReceiptedReuse', definition: 'A mathematical mapping, analogy, invariant, theorem candidate, or model translation may be reused only within the scope allowed by its receipt.', preserveAcrossModels: ['receipt status', 'reuse permission', 'model scope', 'limitations'], failureModes: ['old mapping reused in wrong model', 'limitation dropped', 'unreceipted claim retrieved as trusted'], receiptRequired: true };

export const MATH_INVARIANTS: Map<string, MathInvariant> = new Map([
    ['MINV_MATH_001', MINV_MATH_001], ['MINV_MATH_002', MINV_MATH_002], ['MINV_MATH_003', MINV_MATH_003], ['MINV_MATH_004', MINV_MATH_004], ['MINV_MATH_005', MINV_MATH_005],
    ['MINV_MATH_006', MINV_MATH_006], ['MINV_MATH_007', MINV_MATH_007], ['MINV_MATH_008', MINV_MATH_008], ['MINV_MATH_009', MINV_MATH_009], ['MINV_MATH_010', MINV_MATH_010],
    ['MINV_MATH_011', MINV_MATH_011], ['MINV_MATH_012', MINV_MATH_012], ['MINV_MATH_013', MINV_MATH_013], ['MINV_MATH_014', MINV_MATH_014], ['MINV_MATH_015', MINV_MATH_015],
    ['MINV_MATH_016', MINV_MATH_016], ['MINV_MATH_017', MINV_MATH_017], ['MINV_MATH_018', MINV_MATH_018], ['MINV_MATH_019', MINV_MATH_019], ['MINV_MATH_020', MINV_MATH_020],
    ['MINV_MATH_021', MINV_MATH_021], ['MINV_MATH_022', MINV_MATH_022], ['MINV_MATH_023', MINV_MATH_023], ['MINV_MATH_024', MINV_MATH_024], ['MINV_MATH_025', MINV_MATH_025],
]);
export function getMathInvariant(id: string): MathInvariant | undefined { return MATH_INVARIANTS.get(id); }
export function listReceiptRequiredMath(): MathInvariant[] { return [...MATH_INVARIANTS.values()].filter(m => m.receiptRequired); }